### ISSUE TITLE
Add privacy policy text in a separate page 

### ISSUE THREAD

**Issue by quicola** [Grrrow/soulmate-landing#11]
the link is currently dead and it need to point to [https://solvmate.co/legal/privacy-policy] with the privacy policy here: https://docs.google.com/document/d/1auEXZjAqBbzMMQJPpOP9UWxiegxfv3acJSw5E08MC7Q/edit?usp=sharing
(leave out the sentence about terms of use for now)

**Comment by PabloCarmona** [comment]
added and linked
