### ISSUE TITLE
Remove terms from the copy

### ISSUE THREAD

**Issue by quicola** [Grrrow/soulmate-landing#13]
for now, while I don't have a lawyer take a look.

**Comment by quicola** [comment]
once I have validated, we'll need to point to https://solvmate.co/legal/terms-of-use with this copy https://docs.google.com/document/d/1SJQVQEZEpx2ijjqnn11OnujpNr4PYZm-1dsLQK5X6Nc/edit?usp=sharing

**Comment by quicola** [comment]
on the main page, just needs to say: "Read our privacy policy related to any information you may share with us. Thank you."

**Comment by PabloCarmona** [comment]
Done! We can come back again once we have it sorted out with the lawyer.
