### ISSUE TITLE
add group selecting instead of free test to the "join waitlist" form

### ISSUE THREAD

**Issue by quicola** [Grrrow/soulmate-landing#3]
I'd like to use SolvMate to: 
  select all that apply (radio buttons):
- meet new people
- understand speakers of other languages 
- learn and practice other languages

**Comment by quicola** [comment]
Mejor asi:
* meet new people online
* meet new people in the real world (events, festivals, etc)
* talk with somebody 
* discuss topics I am interested in with kindred spirits
* talk to people in other languages (in my language)
* practice other languages with real people
* conduct business
* other
"tell us more!" [text box with 1 line of space]

**Comment by PabloCarmona** [comment]
Added in the lasts commits
