### ISSUE TITLE
Less space between Contact us and "we value"

### ISSUE THREAD

**Issue by quicola** [Grrrow/soulmate-landing#8]
it is the header of that section, so it needs to be closer together

**Comment by quicola** [comment]
take the same distance between Our Mission and the text below and apply it to Our Technology and Contact us

**Comment by PabloCarmona** [comment]
reduced for contact section, don't know what mean for technology. Yo want to reduce space also in that section? Is the same as the others

**Comment by quicola** [comment]
SolvMate leverages AI in 3 major ways**:** (instead of .)

**Comment by PabloCarmona** [comment]
Done!
